# Generated by Django 6.0.2 on 2026-04-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_created_at_alter_product_description_and_more'),
    ]

    operations = [
    ]
