# Generated by Django 6.0.2 on 2026-04-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_product_field'),
        ('products', '0004_fix_stock_quantity'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productvariation',
            name='products_pr_product_3e5a9b_idx',
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
    ]
